# Generated by Django 2.1.2 on 2018-10-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('-', 'None')], default='-', max_length=1)),
                ('id_type', models.CharField(choices=[('dni', 'D.N.I.'), ('lc', 'L.C.'), ('oth', 'Other')], max_length=3)),
                ('id_number', models.CharField(max_length=50)),
            ],
        ),
    ]
