# Generated by Django 2.1.2 on 2018-10-30 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ancestors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='id_type',
            field=models.CharField(choices=[('DNI', 'D.N.I.'), ('LC', 'L.C.'), ('oth', 'Other')], max_length=3),
        ),
        migrations.AddField(
            model_name='file',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancestors.Person'),
        ),
    ]
